# Generated by Django 5.2.6 on 2025-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='Do Something', max_length=1000),
        ),
    ]
