from django.db import models



LANGUAGES_DICT = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'az': 'azerbaijani',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'ceb': 'cebuano',
    'ny': 'chichewa',
    'zh-cn': 'chinese (simplified)',
    'zh-tw': 'chinese (traditional)',
    'co': 'corsican',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'gl': 'galician',
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'haw': 'hawaiian',
    'iw': 'hebrew',
    'he': 'hebrew',
    'hi': 'hindi',
    'hmn': 'hmong',
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jw': 'javanese',
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'ko': 'korean',
    'ku': 'kurdish (kurmanji)',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mn': 'mongolian',
    'my': 'myanmar (burmese)',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'gd': 'scots gaelic',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
    'sd': 'sindhi',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'sv': 'swedish',
    'tg': 'tajik',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'vi': 'vietnamese',
    'cy': 'welsh',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu',
}


class LanguageChoice(models.TextChoices):
    AFRIKAANS = 'af', 'afrikaans',
    ALBANIAN = 'sq', 'albanian',
    AMHARIC = 'am', 'amharic',
    ARABIC = 'ar', 'arabic',
    ARMENIAN = 'hy', 'armenian',
    AZERBAIJANI = 'az', 'azerbaijani',
    BASQUE = 'eu', 'basque',
    BELARUSIAN = 'be', 'belarusian',
    BENGALI = 'bn', 'bengali',
    BOSNIAN = 'bs', 'bosnian',
    BULGARIAN = 'bg', 'bulgarian',
    CATALAN = 'ca', 'catalan',
    CEBUANO = 'ceb', 'cebuano',
    CHICHEWA = 'ny', 'chichewa',
    CHINESE_SIMPLIFIED = 'zh-n', 'chinese_simplified)',
    CHINESE_TRADITIONAL = 'zh-w', 'chinese (traditional)',
    CORSICAN = 'co', 'corsican',
    CROATIAN = 'hr', 'croatian',
    CZECH = 'cs', 'czech',
    DANISH = 'da', 'danish',
    DUTCH = 'nl', 'dutch',
    ENGLISH = 'en', 'english',
    ESPERANTO = 'eo', 'esperanto',
    ESTONIAN = 'et', 'estonian',
    FILIPINO = 'tl', 'filipino',
    FINNISH = 'fi', 'finnish',
    FRENCH = 'fr', 'french',
    FRISIAN = 'fy', 'frisian',
    GALICIAN = 'gl', 'galician',
    GEORGIAN = 'ka', 'georgian',
    GERMAN = 'de', 'german',
    GREEK = 'el', 'greek',
    GUJARATI = 'gu', 'gujarati',
    HAITIAN_CREOLE = 'ht', 'haitin creole',
    HAUSA = 'ha', 'hausa',
    HAWAIIAN = 'haw', 'hawaiian',
    HEBREW = 'iw', 'hebrew',
    HEBREW2 = 'he', 'hebrew',
    HINDI = 'hi', 'hindi',
    HMONG = 'hmn', 'hmong',
    HUNGARIAN = 'hu', 'hungarian',
    ICELANDIC = 'is', 'icelandic',
    IGBO = 'ig', 'igbo',
    INDONESIAN = 'id', 'indonesian',
    IRISH = 'ga', 'irish',
    ITALIAN = 'it', 'italian',
    JAPANESE = 'ja', 'japanese',
    JAVANESE = 'jw', 'javanese',
    KANNADA = 'kn', 'kannada',
    KAZAKH = 'kk', 'kazakh',
    KHMER = 'km', 'khmer',
    KOREAN = 'ko', 'korean',
    KURDISH_KURMANJI = 'ku', 'kurdish (kurmanji)',
    KYRGYZ = 'ky', 'kyrgyz',
    LAO = 'lo', 'lao',
    LATIN = 'la', 'latin',
    LATVIAN = 'lv', 'latvian',
    LITHUANIAN = 'lt', 'lithuanian',
    LUXEMBOURGISH = 'lb', 'luxembourgish',
    MACEDONIAN = 'mk', 'macedonian',
    MALAGASY = 'mg', 'malagasy',
    MALAY = 'ms', 'malay',
    MALAYALAM = 'ml', 'malayalam',
    MALTESE = 'mt', 'maltese',
    MAORI = 'mi', 'maori',
    MARATHI = 'mr', 'marathi',
    MONGOLIAN = 'mn', 'mongolian',
    MYANMAR_BURMESE_ = 'my', 'myanmar (burmese)',
    NEPALI = 'ne', 'nepali',
    NORWEGIAN = 'no', 'norwegian',
    ODIA = 'or', 'odia',
    PASHTO = 'ps', 'pashto',
    PERSIAN = 'fa', 'persian',
    POLISH = 'pl', 'polish',
    PORTUGUESE = 'pt', 'portuguese',
    PUNJABI = 'pa', 'punjabi',
    ROMANIAN = 'ro', 'romanian',
    RUSSIAN = 'ru', 'russian',
    SAMOAN = 'sm', 'samoan',
    SCOTS_GAELIC = 'gd', 'scos gaelic',
    SERBIAN = 'sr', 'serbian',
    SESOTHO = 'st', 'sesotho',
    SHONA = 'sn', 'shona',
    SINDHI = 'sd', 'sindhi',
    SINHALA = 'si', 'sinhala',
    SLOVAK = 'sk', 'slovak',
    SLOVENIAN = 'sl', 'slovenian',
    SOMALI = 'so', 'somali',
    SPANISH = 'es', 'spanish',
    SUNDANESE = 'su', 'sundanese',
    SWAHILI = 'sw', 'swahili',
    SWEDISH = 'sv', 'swedish',
    TAJIK = 'tg', 'tajik',
    TAMIL = 'ta', 'tamil',
    TELUGU = 'te', 'telugu',
    THAI = 'th', 'thai',
    TURKISH = 'tr', 'turkish',
    UKRAINIAN = 'uk', 'ukrainian',
    URDU = 'ur', 'urdu',
    UYGHUR = 'ug', 'uyghur',
    UZBEK = 'uz', 'uzbek',
    VIETNAMESE = 'vi', 'vietnamese',
    WELSH = 'cy', 'welsh',
    XHOSA = 'xh', 'xhosa',
    YIDDISH = 'yi', 'yiddish',
    YORUBA = 'yo', 'yoruba',
    ZULU = 'zu', 'zulu'