# Generated by Django 5.2.6 on 2025-09-04 05:26

import plugins.code_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.CharField(default=plugins.code_generator.generateUniqueId, max_length=15, primary_key=True, serialize=False),
        ),
    ]
